language: bash
sudo: true
os:
  - linux
dist:
  - xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
  - leanpkg configure
  - curl -O https://raw.githubusercontent.com/leanprover-community/mathlib/master/scripts/remote-install-update-mathlib.sh -sSf
  - chmod +x remote-install-update-mathlib.sh
  - yes | bash remote-install-update-mathlib.sh
  - source $HOME/.profile
  - update-mathlib
jobs:
  include:
    - env: TASK="check build"
      language: bash
      script:
        - leanpkg build
