language: bash
sudo: true
os:
  - linux
dist:
  - xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3 python3-pip
  - sudo pip3 install mathlibtools
install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - if [ "$GITHUB_CRED" != "" ]; then git config --add github.oauthtoken $GITHUB_CRED; echo setting up GitHub credentials; else echo no GitHub credentials available; fi
  - leanpkg configure
  - leanproject get-mathlib-cache
jobs:
  include:
    - env: TASK="check build"
      language: bash
      script:
        - travis_wait leanpkg build
