[package]
name = "lean-perfectoid-spaces"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "b37526407ed1846f29dcdfb976554daf7f8a983e"}
