[package]
name = "lean-perfectoid-spaces"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "a52c2400402658fe10e999db35afe43cddad89ab"}
